-keep class com.google.mlkit.vision.text.** { *; }
-keep class com.google.mlkit.vision.barcode.** { *; }
-keep class com.google.mlkit.vision.objects.** { *; }
-keep class com.google.mlkit.vision.common.** { *; }
-keep class com.google.mlkit.** { *; }
-dontwarn com.google.mlkit.**